### ISSUE TITLE
Drop elm- from package name

### ISSUE THREAD

**Issue by jvoigtlaender** [elm-community/lazy-list#1]
As per https://github.com/elm-community/Manifesto/issues/27, and in particular this discussion: https://github.com/elm-community/Manifesto/issues/27#issuecomment-219725390.

**Comment by jvoigtlaender** [comment]
@mgold, as the maintainer here, do you want to do this?

**Comment by mgold** [comment]
I'm worried about breaking dependent packages. When moving the repo, a redirect is set up, but the tags refer to both "versions". Luckily, the library is currently on 1.0.1, so I can delete the 1.0.0 tag and release that under the new name. Sound good?

**Comment by jvoigtlaender** [comment]
@mgold, this has been discussed in other threads, right? And several packages have already made the equivalent move. Was there any major outage from this? Or is the situation here somehow special/different from the other cases?

**Comment by mgold** [comment]
I don't think so, just being careful.

**Comment by jvoigtlaender** [comment]
Ping.

**Comment by mgold** [comment]
I'll go ahead and do this for 0.18.

**Comment by eeue56** [comment]
0.18 is in alpha.. doing so already means now no updates to elm-lazy-list for 0.17 can happen.

**Comment by eeue56** [comment]
@mgold doing the change this way has broken all 0.17 builds that rely on elm-lazy-list.

```
noah@noah-Swanky:~/dev/f$ elm-package install elm-community/elm-lazy-list
To install elm-community/elm-lazy-list I would like to add the following
dependency to elm-package.json:

    "elm-community/elm-lazy-list": "1.3.0 <= v < 2.0.0"

May I add that to elm-package.json for you? [Y/n] y

Some new packages are needed. Here is the upgrade plan.

  Install:
    elm-community/elm-lazy-list 1.3.0
    elm-lang/core 4.0.5
    elm-lang/html 1.1.0
    elm-lang/lazy 1.0.0
    elm-lang/virtual-dom 1.1.1

Do you approve of this plan? [Y/n] y
Starting downloads...

  ● elm-lang/lazy 1.0.0
  ● elm-lang/virtual-dom 1.1.1
  ● elm-lang/html 1.1.0
  ● elm-lang/core 4.0.5
Error: Problem when downloading the elm-community/elm-lazy-list 1.3.0 code.

  ✗ elm-community/elm-lazy-list 1.3.0

```

**Comment by eeue56** [comment]
I'm going to fix it.

**Comment by eeue56** [comment]
I've fixed the problem by making elm-community/elm-lazy-list exist again. Please note that doing this without getting a second pair of eyes means that all our builds started failing.

![screen shot 2016-10-15 at 09 11 50](https://cloud.githubusercontent.com/assets/1139198/19408190/ad6c4e1a-92b7-11e6-9da0-7b42476e6d51.png)

**Comment by jvoigtlaender** [comment]
Seems this can be closed.

**Comment by mgold** [comment]
Oh no! So sorry for the trouble. I expected that an `elm-lazy-list` redirect would be left behind.
