### ISSUE TITLE
What license is this released under?

### ISSUE THREAD

**Issue by naddeoa** [elm-community/lazy-list#7]
Hey again!

I can only use certain licenses for my current work and I noticed there is no LICENSE file. Do you think you could add one?

**Comment by mgold** [comment]
Pretty much everything in Elm is released under BSD-3. I can add the LICENSE file to make it official, but first, may I ask if that's an acceptable license for your work?

**Comment by naddeoa** [comment]
Definitely. Pretty much anything Apache, BSD, MIT is fine. I just can't actually use it without having that license file unfortunately. I know it's dumb but that's the way things are it seems.

That would be greatly appreciated! I have the same request for your shrink library too, which would unblock the entire dependency graph of elm-test for me.

**Comment by mgold** [comment]
Great, I'd love to make that happen!

**Comment by naddeoa** [comment]
Awesome, thanks for the quick turn around
